configuration: Release
pull_requests:
  do_not_increment_build_number: true
skip_tags: true

notifications:
- provider: GitHubPullRequest
  on_build_success: true
  on_build_failure: true

branches:
  only:
    - master
    - develop

cache:
  - packages -> **\packages.config

before_build:
  - nuget restore

test:
  assemblies:
    - '**\bin\$(configuration)\*.test.dll'

artifacts:
  - path: src\PowerShell\bin\$(configuration)
    name: msi # confusing name of zip default extraction directory
    type: zip

  - path: src\PowerShell\bin\$(configuration)\*.nupkg
    name: package

  - path: src\PowerShell\bin\$(configuration)\*.symbols.nupkg
    name: symbols

  - path: src\Setup\bin\$(configuration)\**\*.msi
    name: installer

deploy:
  - provider: GitHub
    description: 'Release of version $(appveyor_build_version)'
    auth_token:
      secure: 5K94QY8dHKlbjvlBpQaXwAkmDf+LQE3g5WlU9snnNMjDjf0UT4xDoOBCLWcmwZOm
    artifact: installer, package
    on:
      branch: master

  - provider: NuGet
    server: https://powershellgallery.com
    api_key:
      secure: 4STrzCp6wDsDBj/wCtmImMVL7wUI8DCGjdMBXGqQf9JZJ8LjmW5YSY8wtcHAv0XW
    artifact: package
    skip_symbols: true
    on:
      branch: master

  - provider: NuGet
    server: https://nuget.smbsrc.net/
    auth_token:
      secure: WPxjuSouwbCdM6I771BfIbOk8gA883+l9RKUCfFknaUT1vYPmTpT2ABF9r+J0JgR
    artifact: symbols
    on:
      branch: develop
