configuration: Release

before_build:
  - nuget restore

test:
  assemblies:
    - '**\bin\$(configuration)\*.test.dll'

artifacts:
  - path: src\PowerShell\bin\$(configuration)
    name: msi # confusing name of zip default extraction directory
    type: zip

  - path: src\PowerShell\bin\$(configuration)\*.nupkg
    name: package

  - path: src\Setup\bin\$(configuration)\**\*.msi
    name: installer

deploy:
  - provider: GitHub
    description: 'Continuous Deployment'
    auth_token:
      secure: 5K94QY8dHKlbjvlBpQaXwAkmDf+LQE3g5WlU9snnNMjDjf0UT4xDoOBCLWcmwZOm
    artifact: installer, package
    on:
      branch: master

  - provider: NuGet
    server: https://powershellgallery.com/api/v2
    api_key:
      secure: 4STrzCp6wDsDBj/wCtmImMVL7wUI8DCGjdMBXGqQf9JZJ8LjmW5YSY8wtcHAv0XW
    artifact: package
    on:
      branch: master
